name: Gradle Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gradle-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v5
      - name: Test on Java 17
        run: >-
          xvfb-run -a ./gradlew -g .gradle-user-home
          cleanTest test verifyNoRuntimeDependencies
          --info --no-daemon --stacktrace
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Build and verify documentation on Java 25
        run: >-
          xvfb-run -a ./gradlew -g .gradle-user-home
          clean assemble javadoc verifyNoRuntimeDependencies
          --info --no-daemon --stacktrace
      - name: Upload JAR
        uses: actions/upload-artifact@v7
        with:
          name: javif.jar
          path: build/libs/*.jar
